modLoader="javafml" #mandatory
loaderVersion="[36,)"

# The license for your mod. This is mandatory and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All Rights Reserved"

[[mods]]
modId="nostrumaetheria"
version="${file.jarVersion}"
displayName="Nostrum Aetheria"
#logoFile="examplemod.png" #optional
authors="Skyler Manzanares"
description='''
Magical energy add-on for Nostrum Magica
'''

[[dependencies.nostrumaetheria]]
	modId="forge"
	mandatory=true
	versionRange="[36,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.nostrumaetheria]]
	modId="curios"
	mandatory=false
	versionRange="[1.16.4-4.0.3.5,)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.nostrumaetheria]]
	modId="nostrummagica"
	mandatory=true
	versionRange="[1.16.5-1.11.0,)"
	ordering="AFTER"
	side="BOTH"