modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"

# The license for your mod. This is mandatory and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="${mod_license}"

[[mods]]
modId="${mod_id}" 
version="${mod_version}"
displayName="${mod_name}"
#logoFile="examplemod.png" #optional
authors="{$mod_authors}"
description='''${mod_description}'''

[[dependencies.nostrumaetheria]]
	modId="forge"
	mandatory=true
	versionRange="${loader_version_range}"
	ordering="NONE"
	side="BOTH"

[[dependencies.nostrumaetheria]]
	modId="curios"
	mandatory=false
	versionRange="[${curios_version},)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.nostrumaetheria]]
	modId="nostrummagica"
	mandatory=true
	versionRange="[${nostrummagica_version},)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.nostrumaetheria]]
	modId="petcommand"
	mandatory=true
	versionRange="[${petcommand_version},)"
	ordering="AFTER"
	side="BOTH"